@host=http://localhost:3000/api

# @name signup
POST  {{host}}/users/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "username": "johndoe",
    "email": "johndoe@gmail.com",
    "password":""
}
###