
@host=http://localhost:3000/api

# @name signup
POST  {{host}}/users/register
Content-Type: application/json

{
    "firstName": "john",
    "lastName": "doe",
    "username": "john",
    "email": "johndoe@gmail.com",
    "password": ""
}
###

# @name login
# @prompt username
# @prompt pass
POST  {{host}}/users/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{pass}}"
}
###

# @name createBoard
POST  {{host}}/boards/
Content-Type: application/json

{
    "name": "proyect test",
    "description":"board test"
}
###
@idBoard = {{createBoard.response.body.board.id}}

# @name updateBoard
PUT  {{host}}/boards/{{idBoard}}
Content-Type: application/json

{
    "name": "board update",
    "description":"board update"
}
###

# @name getUserBoards
GET   {{host}}/boards/
###

# @name getBoard
GET   {{host}}/boards/{{idBoard}}
###

# @name deleteBoard
DELETE {{host}}/boards/{{idBoard}}
###

# @name createBoardColumn
POST  {{host}}/columns/
Content-Type: application/json

{
    "name": "column test",
    "BoardId": "{{idBoard}}"
}
###
@idColumn = {{createBoardColumn.response.body.column.id}}
# @name updateColumnIndex
PATCH {{host}}/columns/{{idColumn}}/index
Content-Type: application/json

{
    "index":1
}
###

# @name deleteColumn
DELETE {{host}}/columns/{{idColumn}}
Content-Type: application/json
###

# @name updateColumnName
PATCH {{host}}/columns/{{idColumn}}/name
Content-Type: application/json

{
    "name":"Test updated name"
}
###