
@host=http://localhost:4000/api

# @name signup
POST  {{host}}/users/register
Content-Type: application/json

{
    "firstName": "john",
    "lastName": "doe",
    "username": "johndoe",
    "email": "johndoe@gmail.com",
    "password": ""
}
###

# @name login
# @prompt username
# @prompt pass
POST  {{host}}/users/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{pass}}"
}
###
@username= {{login.response.body.profile.username}}
# @name getProfileUser
GET {{host}}/users/profile
Content-Type: application/json
###
# @name verifyToken
GET {{host}}/users/verify
Content-Type: application/json
###

# @name logout
GET {{host}}/users/logout
Content-Type: application/json
###

# @name uploadProfileImage
PATCH {{host}}/users/profile/picture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profile_picture"; filename="profile-picture.png"
Content-Type: image/png

< ./uploads/profile-pictures/default.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# @name createBoard
POST  {{host}}/boards/
Content-Type: application/json

{
    "name": "proyect test",
    "description":"board test"
}
###
@boardId = {{createBoard.response.body.board.id}}

# @name updateBoard
PUT  {{host}}/boards/{{boardId}}
Content-Type: application/json

{
    "name": "board update",
    "description":"board update"
}
###

# @name getUserBoards
GET   {{host}}/boards/
###

# @name getBoard
GET   {{host}}/boards/{{boardId}}
###

# @name deleteBoard
DELETE {{host}}/boards/{{boardId}}
###

# @name createBoardColumn
POST  {{host}}/columns/
Content-Type: application/json

{
    "name": "column test 1",
    "BoardId": "{{boardId}}"
}
###
@columnId = {{createBoardColumn.response.body.column.id}}
# @name updateColumnPosition
PATCH {{host}}/columns/{{columnId}}/position
Content-Type: application/json

{
    "position":1
}
###

# @name deleteColumn
DELETE {{host}}/columns/{{columnId}}
Content-Type: application/json
###

# @name updateColumnName
PATCH {{host}}/columns/{{columnId}}/name
Content-Type: application/json

{
    "name":"Test updated name"
}
###

# @name addTask
POST {{host}}/tasks
Content-Type: application/json

{
    "name":"task test 1",
    "ColumnId":"{{columnId}}",
    "BoardId":"{{boardId}}"
}
###
@taskId = {{addTask.response.body.task.id}}
# @name getTask
GET {{host}}/tasks/{{taskId}}
Content-Type: application/json

###

# @name updateTaskPosition
PATCH {{host}}/tasks/{{taskId}}/position
Content-Type: application/json

{
    "newPosition":1,
    "newColumnId":"{{columnId}}"
}
###

# @name updateTaskName
PATCH {{host}}/tasks/{{taskId}}/name
Content-Type: application/json

{
    "name":"Updated name"
}
###

# @name deleteTask
DELETE {{host}}/tasks/{{taskId}}
###